name: Reproduce

on: watch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: github.actor == 'francisfuzz'
        uses: actions/checkout@v1

      - if: github.actor == 'francisfuzz'
        name: Attempt to curl Okta 100 times (in container)
        run: docker-compose run api bash -c "for ((i=1;i<=100;i++)); do curl https://dev-698520.okta.com > /dev/null ; done"

      - if: github.actor == 'francisfuzz'
        name: Attempt to curl Okta 100 times (in VM)
        run: |
          for ((i=1;i<=100;i++)); do curl https://dev-698520.okta.com > /dev/null ; done

      - if: github.actor == 'francisfuzz'
        name: Attempt to curl GitHub API 100 times (in container)
        run: |
          docker-compose run api bash -c "for ((i=1;i<=100;i++)); do curl -H \"authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com > /dev/null ; done"

      - if: github.actor == 'francisfuzz'
        name: Attempt to curl GitHub API 100 times (in VM)
        run: |
          for ((i=1;i<=100;i++)); do curl -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com > /dev/null ; done
