name: Reproduce

on: watch

jobs:
  build:
    if: github.actor == 'francisfuzz'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [wst.msedge.net, hk2.msedge.net, lon21.msedge.net, dev-698520.okta.com]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Hit ${{ matrix.target }}.msedge.net 100x (VM)
      run: |
        for ((i=1;i<=100;i++));
        do 
          curl http://${{ matrix.target }} > /dev/null ;
        done

    - name: Hit ${{ matrix.target}} 100x (container)
      run: |
        docker-compose run api bash -c "for ((i=1;i<=100;i++)); do curl http://${{ matrix.target }} > /dev/null ; done"
