name: Reproduce

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Print /lib/systemd/system/docker.service
        run: sudo cat /lib/systemd/system/docker.service

      - name: Patch docker MTU
        run: |
          sudo sed -i 's/ExecStart=\/usr\/bin\/dockerd -H fd\:\/\/ --containerd=\/run\/containerd\/containerd.sock/ExecStart=\/usr\/bin\/dockerd --mtu 1400 -H fd\:\/\/ --containerd=\/run\/containerd\/containerd.sock/g' /lib/systemd/system/docker.service
          sudo systemctl daemon-reload
          sudo service docker restart

      - name: Print /lib/systemd/system/docker.service
        run: sudo cat /lib/systemd/system/docker.service
