name: Reproduce

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check docker process
        run: ps aux | grep docker

      - name: Patch docker MTU
        run: sudo sed -i 's/ExecStart=\/usr\/bin\/dockerd -H fd\:\/\//ExecStart=\/usr\/bin\/dockerd --mtu 1400 -H fd\:\/\//' /lib/systemd/system/docker.service

      - name: daemon-reload
        run: sudo systemctl daemon-reload

      - name: Restart Docker
        run: sudo service docker restart

      - name: Check docker process
        run: ps aux | grep docker

      - name: Attempt to curl Google 100 times
        run: docker run node:12 bash -c "for ((i=1;i<=100;i++)); do curl https://google.com > /dev/null ; done"

      - name: Attempt to curl Okta 100 times
        run:  docker run node:12 bash -c "for ((i=1;i<=100;i++)); do curl https://okta.com > /dev/null ; done"

      - name: Check pmtu
        run: |
          apt-get update
          apt-get install iputils-tracepath
          tracepath -n dev-698520.okta.com

      - name: Attempt to curl Okta subdomain 100 times
        run:  docker run node:12 bash -c "for ((i=1;i<=100;i++)); do curl https://dev-698520.okta.com > /dev/null ; done"
