name: Reproduce

on: watch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: github.actor == 'francisfuzz'
        uses: actions/checkout@v1

      - if: github.actor == 'francisfuzz'
        name: Attempt to curl Okta 100 times
        run: |
          for ((i=1;i<=100;i++)); 
            do curl https://dev-698520.okta.com > /dev/null ; 
          done

      - if: github.actor == 'francisfuzz'
        name: Attempt to curl google 100 times
        run: |
          for ((i=1;i<=100;i++)); 
            do curl -vL https://google.com > /dev/null ; 
          done
