name: Reproduce

on: watch

jobs:
  request:
    if: github.actor == 'chkimes'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
        
    - name: Start tcpdump
      run: |
        sudo tcpdump -i eth0 -nn -w okta.dmp host 34.223.95.128 or host 34.223.95.129 or host 34.223.95.130 &

    - name: Hit okta 10x
      run: |
        for ((i=1;i<=10;i++)); do curl -v https://dev-698520.okta.com ; done

    - name: Hit okta 10x (container)
      run: |
        docker-compose run api bash -c "for ((i=1;i<=10;i++)); do curl -v https://dev-698520.okta.com ; done"
    
    - name: Kill tcpdump
      run: |
        sudo kill -2 $(ps -e | pgrep tcpdump)

    - name: Upload to file.io
      run: |
        sudo curl -F 'file=@okta.dmp' https://file.io/?expires=1
