name: Reproduce

on: watch

jobs:
  request:
    if: github.actor == 'francisfuzz'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [https://wst.msedge.net, https://hk2.msedge.net, https://lon21.msedge.net, https://dev-698520.okta.com]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Hit ${{ matrix.target }} 100x (VM)
      run: |
        for ((i=1;i<=100;i++)); do curl -v ${{ matrix.target }} ; done

    - name: Hit ${{ matrix.target}} 100x (container)
      run: |
        docker-compose run api bash -c "for ((i=1;i<=100;i++)); do curl -v ${{ matrix.target }} ; done"
